### ISSUE TITLE
Jar file not supported in Eclipse

### ISSUE THREAD

**Issue by olivetechnologies** [nrinaudo/kantan.csv#100]
I found it pleasing to find an API like kantan  for reading csv in scala. 
However i am having issues using this with eclipse scala ide. After downloading the jar file "kantan.csv_2.11-0.2.1" from Maven repository. The import statement "import kantan.csv._ " is having an error "could not find kantan".
How do i overcome this error. 
Thanks for your swift response.

**Comment by nrinaudo** [comment]
Honestly, I do not know. I don't use eclipse, don't know how it integrates with maven.

There's strictly no reason for kantan.csv to behave any differently than any other library, since it's just a JAR file published on maven. The best I can suggest is take whatever worked for another library and do the same thing?

**Comment by nrinaudo** [comment]
This was resolved in a gitter conversation and nothing to do with kantan.csv.
