### ISSUE TITLE
escape quotation

### ISSUE THREAD

**Issue by SamanSattari** [nrinaudo/kantan.csv#159]
I just started to use Katan.csv. I think it is great that I can easily read my csv rows as `case class`. I have a small problem with the library that I cannot figure out. It could be that I don't fully understand how it works. 
In the CSV files that I am reading, quotations has been used as a metric and not as quotations. This means that there is no end quote character ex. 2/8". There are also many other special characters used in the file. I want to be able to read csv without specifying quotation character. 
I see in the code is that it used to be possible to do so by using:
`asCsvReader[B: HeaderDecoder](sep: Char, header: Boolean)(implicit e: ReaderEngine)`
but this is now deprecated and I have to use
 `asCsvReader[B: HeaderDecoder](conf: CsvConfiguration)(implicit e: ReaderEngine)` which requires `CsvConfiguration`. 
`CsvConfiguration` requires a quote character. Is there a way to skip specifying any character as quote character?

**Comment by nrinaudo** [comment]
Well, no, it never was possible to not specify a quote character - the type signature you pasted has `sep` as non-optional. I don't know how familiar you are with the language, so you may already be aware of this, but tend to use `Option[Char]` to mean an optional `Char`, and ban the use of `null`, if this what you thought of using.

kantan.csv does not support not having a quote character, simply because it's required by specifications to deal with column and cell separators within a cell.

I can think of two possible solutions:
* use an exotic character, such as unicode 0 maybe? and live with the fact that things will sometimes crash because you can't represent all CSV data without quote characters
* use one of the supported [external engines](https://nrinaudo.github.io/kantan.csv/engines.html) and see whether they don't support the behaviour you need.

That being said, I feel maybe there's something more to your use case than what you say here, since it seems to work just fine:

```scala
"1,2,2/8\"".readCsv[List, (Int, Int, String)](rfc)
res0: List[kantan.csv.ReadResult[(Int, Int, String)]] = List(Right((1,2,2/8")))
```

**Comment by SamanSattari** [comment]
Hi, 
After what you mentioned, I went and copied the rows that I thought were not working because of quotes in separate file and tested them separately. I can confirm that those lines work with the library. So the issue might be some other parts of the csv or it might be with my code as I do some transformations afterwards.

Thanks for helping me debug this :).

**Comment by SamanSattari** [comment]
I found the problematic line in the csv. The issue is that a column starts with quotation but it finishes the quotation before the column ends. Here is the example:
`"1,2,\"2/8\" here, 1".readCsv[List, (Int, Int, String, Int)](rfc)`

If the quotation is any where else in the column there will be no issue:
`"1,2,here \"2/8\" here, 1".readCsv[List, (Int, Int, String, Int)](rfc)`

**Comment by nrinaudo** [comment]
This is not legal CSV. See the corresponding [RFC](https://tools.ietf.org/html/rfc4180), point 7.

```scala
scala> "1,2,\"\"\"2/8\" here\", 1".readCsv[List, (Int, Int, String, Int)](rfc)
res0: List[kantan.csv.ReadResult[(Int, Int, String, Int)]] = List(Right((1,2,"2/8" here,1)))
```
