### ISSUE TITLE
Errors thrown when constructing a class from a row aren't caught

### ISSUE THREAD

**Issue by joshuaconner** [nrinaudo/kantan.csv#168]
Running 0.4.0, here's a simplified version of what we're running in to:

```scala
import java.io.StringReader

import kantan.csv._
import kantan.csv.ops._
import kantan.csv.generic._

final case class Person(id: Int, name: String, flag: Boolean)
final case class EvenPerson(id: Int, name: String, flag: Boolean) {
  require(id % 2 == 0, "id is odd")
}

val csv = """id,name,flag
1,Dane,true
2,Kay,true
"""
// expected: returs a list of length 2. actual: returns a list of length 2.
new StringReader(csv).asCsvReader[Person](rfc).collect { case Right(a) ⇒ a }.toList
// expected: returns a list of length 1. actual: throws IllegalArgumentException.
new StringReader(csv).asCsvReader[EvenPerson](rfc).collect { case Right(a) ⇒ a }.toList
```

There are probably better ways for us to structure the code we're writing, but it was also unexpected that this would happen, so we thought we should flag it. I'm happy to make a PR if you're open to a fix but it's a breaking change so I'm not sure. Thanks!

**Comment by nrinaudo** [comment]
Unless I'm missing something, your expectations are not reasonable:
* `EvenPerson` will throw whenever you create an instance where `id` is not even
* you turn CSV data into a stream of `EvenPerson`, building a value of type `EvenPerson` for each row

If your CSV data contains odd identifiers, and your code throws when it encounters an odd identifier, then it's reasonable to expect that applying your code to your CSV data will throw.

There are many ways of working around this, such as:
* not using `require` (lots of people frown on it since exceptions are considered a wart in the language). I would suggest using [refined](https://github.com/fthomas/refined) to enforce the "even" constraint without exceptions.
* decoding the CSV as `Person`, filtering on `_.id % 2 == 0` and then mapping to `EvenPerson`.
* ...
