### ISSUE TITLE
\r\n for new lines is not configurable

### ISSUE THREAD

**Issue by kostaskougios** [nrinaudo/kantan.csv#176]
There doesn't seem to be a config for new lines when writing and I am getting \r\n on my ubuntu dev box. Can this be made configurable?

val rows=Seq(...my case class ...)
out.asCsvWriter(csvConfig).write(rows).close()

(always writes csv files with \r\n)

**Comment by nrinaudo** [comment]
Are you talking about parsing or serialisation?

**Comment by kostaskougios** [comment]
Sorry, I mean't during writing. I've updated my issue's description.

**Comment by nrinaudo** [comment]
Right. That makes sense. kantan.csv will always default to the system's line break.

I'm not sure I'll be changing that any time soon because I do not know of a single CSV parsing software, or CSV parsing library, that doesn't deal with both cases.

On the other hand, it's possible that you might be able to work around this by using a non-default CSV engine. See [the documentation](https://nrinaudo.github.io/kantan.csv/engines.html) for more details.

**Comment by kostaskougios** [comment]
Hi, "kantan.csv will always default to the system's line break". I am on ubuntu so it should be \n, shouldn't it?

Basically it makes testing bit harder as asserting depends on what system you run it on.

**Comment by nrinaudo** [comment]
When you write it that way it does sound weird, you're right. Are you positive your JVM is not configured weirdly? It's a system property, something like `line.separator`.

**Comment by nrinaudo** [comment]
Ah, right. Sorry. You're 100% correct. That's actually by RFC: https://tools.ietf.org/html/rfc4180

So it should not actually depend on the system you run it on, kantan.csv has explicit CRLF in the code.

**Comment by kostaskougios** [comment]
ah ok I see thanks
