### ISSUE TITLE
Support Scala 2.12.0

### ISSUE THREAD

**Issue by ScalaWilliam** [nrinaudo/kantan.csv#58]
Seems to be secretly out.

**Comment by nrinaudo** [comment]
Yeah, I realised that this weekend. I need to look into this though, as there are a few potential roadblocks:
* all dependencies must have 2.12 artifacts, and some are quite obscure.
* 2.12 is Java 8 only, and current artifacts are Java 7. Is there a way to cross-compile smartly, or do I need to drop Java 7 support altogether? Is that actually a problem in the Scala world?

Thoughts on the matter are quite welcome.

**Comment by ScalaWilliam** [comment]
SBT [supports cross-building](http://www.scala-sbt.org/0.13/docs/Cross-Build.html).

1. It appears that scalaz-stream has been moved to another library called fs2. So for a 2.12 build you'd need to be using that as I don't think they'll release a 2.12 for scalaz-stream any more. I created an issue for fs2 to do a 2.12 release: https://github.com/functional-streams-for-scala/fs2/issues/757 as kantan will depend upon it. [kantan build.sbt reference](https://github.com/nrinaudo/kantan.csv/blob/961992bd51c4c1dfce1cbb1564551b7c5e798120/build.sbt#L151)
2. Created an issue for a 2.12 release for: https://github.com/marklister/product-collections/issues/41 - reference: https://github.com/nrinaudo/kantan.csv/blob/961992bd51c4c1dfce1cbb1564551b7c5e798120/build.sbt#L55
3. Created an issue for a 2.12 release for scala-csv: https://github.com/tototoshi/scala-csv/issues/92 - reference: https://github.com/nrinaudo/kantan.csv/blob/961992bd51c4c1dfce1cbb1564551b7c5e798120/build.sbt#L57

You also have a ScalaTest dependency but it should already be published.

2.12 artifacts will have to be Java 8 only, whereas 2.11 (or below) will support Java 7 and above as they should now.

Does this answer your roadblocks?

**Comment by nrinaudo** [comment]
Oh no I know sbt supports cross building - kantan.csv already has published artifacts for 2.11.8 and 2.10.6. What I'm not sure it supports is something like: 2.12.0 -> java 8, 2.11.8 -> java 7, ... I'll look into it.

Regarding scalaz-stream / fs2: you're entirely right, and there's already a ticket (#51) for that. Last time I looked, it meant dropping support for 2.10, which makes me a bit uncomfortable - kantan.csv doesn't have many users, but a significant part of them are running 2.10 (because of spark, mostly).

There are also some "hidden" dependencies - kantan.codecs has a lot of transitive dependencies, including scalaz, cats, shapeless... libraries that I'm pretty sure will get a 2.12.0 release fairly soon, but don't have one yet.

But yeah, the ones you created tickets for were the ones I was worried about. I'm not 100% sure they're still actively maintained. Not necessarily a show stopper, it'll just mean I need to drop them from the benchmarks, but since scala-csv is the main kantan.csv alternative, it'd be a shame. Thanks a lot for creating these tickets by the way, they probably carry more weight from a user than from a competing library author :)

**Comment by nrinaudo** [comment]
Ok, so my worries about needing to drop java 7 support are entirely unfounded. It'll actually require simplifying my build process: nrinaudo/kantan.sbt#6 .

**Comment by ScalaWilliam** [comment]
FS2 unblocked. Updating issue with strikethrough. https://github.com/functional-streams-for-scala/fs2/issues/757#issuecomment-258042536

**Comment by ScalaWilliam** [comment]
scala-csv unblocked: https://github.com/tototoshi/scala-csv/pull/93

**Comment by nrinaudo** [comment]
I think most dependencies are good now, except for `product-collections` which should be soon or could be dropped.

This is going to have to wait on #59 though, which I'm struggling with right now. Feel free to check [what's getting me stuck](http://stackoverflow.com/questions/40390846/deriving-arbitrary-function-instances-using-shapeless-scalacheck) and lending a hand :)

**Comment by ScalaWilliam** [comment]
product-collections unblocked: 
https://github.com/marklister/product-collections/issues/41#issuecomment-258149114

So we're now only blocked on #59  ;)

**Comment by nrinaudo** [comment]
Actually, one more: non/imp#11.

**Comment by nrinaudo** [comment]
Also, I think scala-csv artifacts are not yet published. Only a matter of time until they are, but I can't seem to find them.

**Comment by nrinaudo** [comment]
Regarding scalaz-stream / fs2: turns out supporting fs2 actually means dropping support for 2.10. On the other hand, scalaz-stream now has a 2.12 build.

**Comment by ScalaWilliam** [comment]
Then no need to migrate yet, which is good.

**Comment by nrinaudo** [comment]
Almost there, I think. Still blocked on typelevel/cats#1450, but once that's done it looks pretty straightforward, provided 2.12 doesn't break too many things.

**Comment by nrinaudo** [comment]
Update on this: all dependencies are now available. I need to work out a couple of behavioural changes in implicit resolutions to get tests to compile again, but so far, all tests that compile pass. Shouldn't be much longer.

**Comment by nrinaudo** [comment]
0.1.16-SNAPSHOT has been published with artifacts for Scala 2.12.0. Don't forget to declare the proper snapshot repository if you want to play with this:

```scala
resolvers := Seq(Resolver.sonatypeRepo("snapshots"))
```
