### ISSUE TITLE
CSV Headers 

### ISSUE THREAD

**Issue by D-D-D-D** [nrinaudo/kantan.csv#70]
Hi I just started using kantan and I need some help.  Is it possible to get a list of the headers before decoding  the rows of a csv file. The way I do it now is just reading the first line in, but I was wondering if there is a better way.

**Comment by nrinaudo** [comment]
I assume you mean _decoding_ rather than _encoding_?

Unfortunately, there is currently no way to read the headers in a useable fashion - it's hard to build first-party support for headers when it's an entirely optional and often ignored part of CSV data.

I might try to build optional support for this later, but there is currently no plan for this.

**Comment by D-D-D-D** [comment]
Yes I mean decode thanks for the quick response. I hope it's included in the future.

**Comment by nrinaudo** [comment]
I have working proof of concept. It seems quite clever to me, which is probably a sign that it doesn't actually work as well as I think it does.

It'll still require a non-negligible amount of work, but at least I've now found a way of doing it without breaking backward compatibility, and it will most likely be included in the next release.

**Comment by nrinaudo** [comment]
I realise I'm working on something slightly different from what you're asking. Rather than letting you access the header, which I don't believe will ever happen, the upcoming release will let you use header labels rather than indexes when describing encoders / decoders.

That is, rather than saying "pick field index 3 as an `Int`", you'd say "pick field `id` as an `Int`". Hopefully that's your underlying use case.

**Comment by Jubobs** [comment]
Any progress on this?

**Comment by nrinaudo** [comment]
Depends on what you mean. [This](http://nrinaudo.github.io/kantan.csv/tut/headers.html) is available, if it's what you have in mind.

**Comment by Jubobs** [comment]
@nrinaudo Yes, I only saw that after posting my comment.

My understanding is that `kantan.csv` only supports up to 22 headers. Correct? My use case requires support for an arbitrary number of headers, which I do not know in advance.

**Comment by nrinaudo** [comment]
You could probably do it with any number of headers, if you were willing to write the `HeaderDecoder` instance yourself.

That being said, that's not really the use case I had in mind when writing this, so it might not work for you - I'm not really sure how you could create a decoder, who must be fully known at compile time, from values you don't know until runtime.

**Comment by Jubobs** [comment]
Basically, I want to decode some mandatory fields (say `Year`, `Make`,` Model`) and shove all the others in a `Map[String, String]`:

```
final case class Car(year: Int, make: String, model: String, others: Map[String, String])
```

**Comment by nrinaudo** [comment]
That should be possible. `HeaderDecoder` needs to transform a `Seq[String]` (the header) into a `RowDecoder`, which is basically a `Seq[String] => A` where `A`, in your case, would be `Car`.

So you'd first find the index of your required fields (`year`, `make`, `model`) in the header, then you could conceivably write a `RowDecoder` that picks the right types from these indexes and takes the rest and sticks it into a `Map[String, String`].

It's not going to be pretty, but you could get it work.

**Comment by Jubobs** [comment]
@nrinaudo I'll try! Thanks for your input.

**Comment by nrinaudo** [comment]
Feel free to join the project's gitter so we can talk about this more. Header support is new and there might be rough edges, working with you on your use case could help me work them out.
